Changed the logic to be able to find the last IN event despite its order in the debug records.
thingsboard/thingsboard pull request #10355
Opened 2024-03-12 16:03 UTC by irynamatveieva

## Pull Request description

In case two most recent Debug events in a rule node contain two consecutive OUT messages with no IN, the getLatestRuleNodeDebugInput function can’t find the IN event to populate the test transformer function, so users get a default message and metadata fields:
![image-20220902-075251](https://github.com/thingsboard/thingsboard/assets/101514424/cdbe0a9b-8ccf-4037-b2f9-cad8ddbbd36f)
Changed the logic to be able to find the last IN event despite its order in the debug records. 

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [x] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [x] If new yml property was added: make sure a description is added (above or near the property).

2024-03-12 16:13 UTC, ShvaykaD commented on application/src/main/java/org/thingsboard/server/controller/RuleChainController.java
> +        return eventInfo.getBody();
check for null, if eventInfo is null you will get NPE.

2024-03-12 16:15 UTC, ShvaykaD commented on common/dao-api/src/main/java/org/thingsboard/server/dao/event/EventService.java
> +    EventInfo findLatestDebugRuleNodeInEvent(TenantId tenantId, EntityId entityId);
Let's add optional here.
```suggestion
    Optional<EventInfo> findLatestDebugRuleNodeInEvent(TenantId tenantId, EntityId entityId);
```

2024-03-19 09:47 UTC, ShvaykaD commented on dao/src/test/java/org/thingsboard/server/dao/sql/event/JpaBaseEventDaoTest.java
> +    private RuleNodeDebugEventEntity getDebugEventEntity(UUID eventId, UUID tenantId, UUID entityId) {
```suggestion
    private RuleNodeDebugEventEntity getDebugInEventEntity(UUID eventId, UUID tenantId, UUID entityId) {
```

2024-03-19 09:49 UTC, ShvaykaD commented on dao/src/test/java/org/thingsboard/server/dao/sql/event/JpaBaseEventDaoTest.java
> +        eventDao.saveAsync(event.toData());
```suggestion
        eventDao.saveAsync(event.toData()).get(1, TimeUnit.MINUTES);
```

2024-03-19 09:50 UTC, ShvaykaD commented on dao/src/test/java/org/thingsboard/server/dao/sql/event/JpaBaseEventDaoTest.java
> +        eventDao.saveAsync(event2.toData());
```suggestion
        eventDao.saveAsync(event2.toData()).get(1, TimeUnit.MINUTES);

2024-03-19 09:50 UTC, ShvaykaD commented on dao/src/test/java/org/thingsboard/server/dao/sql/event/JpaBaseEventDaoTest.java
> +        eventDao.saveAsync(event.toData());
use 2 millis sleep in the same way as in other tests.

2024-03-19 09:56 UTC, ShvaykaD requested changes
See my comments added above.

2024-03-20 09:18 UTC, ShvaykaD approved these changes

2024-04-09 10:00 UTC, ViacheslavKlimov commented on application/src/main/java/org/thingsboard/server/controller/RuleChainController.java
> +        return eventInfo == null ? null : eventInfo.getBody();
Use `Optional.ofNullable`

2024-04-10 07:51 UTC, ShvaykaD commented on dao/src/main/java/org/thingsboard/server/dao/event/BaseEventService.java
> +        return event == null ? null : event.toInfo(entityType);
Please use Optional.ofNullable

2024-04-10 10:19 UTC, merged