Mqtt node: added tests
thingsboard/thingsboard pull request #10958
Opened 2024-06-10 12:26 UTC by irynamatveieva

## Pull Request description

Added tests for the mqtt node.

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [x] If new yml property was added: make sure a description is added (above or near the property).

2024-07-29 09:10 UTC, ShvaykaD requested changes

2024-07-29 09:10 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeTest.java
> +        ReflectionTestUtils.setField(mqttNode, "forceAck", true);
to many reflection. Please rewrite tests without them. Our plan was to create a method for getting mqtt client that we will be able to mock and as a result this allow us always call init method when needed.

```
    protected MqttClient getClient(TbContext ctx, MqttClientConfig config) {
        return MqttClient.create(config, null, ctx.getExternalCallExecutor());
    }
```

2024-07-29 09:24 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNodeTest.java
> +    }
what about other fields? If someome for example will set retained message to true, this test will not catch this.

2024-08-06 13:26 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
> +    protected SslContext getSslContext() throws SSLException {
should be private. Use verify on method: prepareMqttClientConfig to check the sslContext.

2024-08-06 14:09 UTC, ShvaykaD requested changes

2024-08-07 09:14 UTC, ShvaykaD approved these changes

2024-08-07 09:22 UTC, ShvaykaD approved these changes

2024-08-09 12:04 UTC, ViacheslavKlimov approved these changes

2024-08-09 12:04 UTC, merged