PubSub node: added tests
thingsboard/thingsboard pull request #11027
Opened 2024-06-17 13:25 UTC by irynamatveieva

## Pull Request description

Added tests for the GCP PubSub node.   

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [x] If new yml property was added: make sure a description is added (above or near the property).

2024-07-29 10:34 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNodeTest.java
> +    public void givenForceAckIsTrueAndMessageAttributesPatterns_whenOnMsg_thenEnqueueForTellNext(
will be nice to add the same test where forceAck is false.

2024-07-29 10:35 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNodeTest.java
> +    public void givenForceAckIsFalseAndErrorOccursOnTheGCP_whenOnMsg_thenTellFailure() {
will be nice to add the same test where forceAck is true.

2024-07-29 10:36 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNodeTest.java
> +        ReflectionTestUtils.setField(node, "forceAck", true);
please replace reflection with corresponding method stubbing.

2024-07-29 10:37 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNodeTest.java
> +        ReflectionTestUtils.setField(node, "forceAck", false);
please replace reflection with corresponding method stubbing.

2024-07-29 10:38 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNodeTest.java
> +    }
please replace reflection with init method invocation.

2024-07-29 10:38 UTC, ShvaykaD requested changes
Please check my comments added above

2024-08-06 14:17 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNode.java
> +    protected Publisher initPubSubClient(TbContext ctx) throws IOException {
package-private

2024-08-06 14:23 UTC, ShvaykaD requested changes

2024-08-06 14:23 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNode.java
> +    protected Publisher initPubSubClient(TbContext ctx) throws IOException {
package-private

2024-08-07 09:24 UTC, ShvaykaD approved these changes

2024-08-09 11:58 UTC, ViacheslavKlimov approved these changes

2024-08-09 11:58 UTC, merged