Change originator node: added tests
thingsboard/thingsboard pull request #11121
Opened 2024-07-02 09:43 UTC by irynamatveieva

## Pull Request description

Added tests for the change originator node.

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [x] If new yml property was added: make sure a description is added (above or near the property).

2024-08-07 12:38 UTC, ShvaykaD requested changes

2024-08-07 12:38 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeTest.java
> +    public void init() throws TbNodeException {
1. why public?
2. why is this method called only in one place, maybe we can remove it?

2024-08-07 12:38 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeTest.java
> +        given(ctxMock.getDbCallbackExecutor()).willReturn(dbExecutor);
duplicate logic. Already mocked in the init method.

2024-08-08 08:27 UTC, ShvaykaD requested changes

2024-08-08 08:27 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeTest.java
> +        assertThat(throwable.getValue()).isInstanceOf(IllegalStateException.class).hasMessage("Failed to found ASSET  entity by name: 'test-asset'!");
```suggestion
        assertThat(throwable.getValue()).isInstanceOf(IllegalStateException.class).hasMessage("Failed to found asset with name 'test-asset'!");
```

2024-08-08 08:27 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeTest.java
> +                .hasMessage("Unexpected entity type TENANT");
```suggestion
                .hasMessage("Unexpected entity type 'TENANT'.");
```

2024-08-08 08:33 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
> +            log.error("Unsupported source type '[{}]'! Only {} types are allowed.", conf.getOriginatorSource(), supportedOriginatorSourcesStr);
```suggestion
            log.error("Unsupported source type '{}'! Only {} types are allowed.", conf.getOriginatorSource(), supportedOriginatorSourcesStr);
```

2024-08-08 08:33 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
> +                log.error("Entity type should be specified if '[{}]' source is selected.", ENTITY_SOURCE);
```suggestion
                log.error("Entity type should be specified if '{}' source is selected.", ENTITY_SOURCE);
```

2024-08-08 08:33 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
> +                log.error("Name pattern should be specified if '[{}]' source is selected.", ENTITY_SOURCE);
```suggestion
                log.error("Name pattern should be specified if '{}' source is selected.", ENTITY_SOURCE);
```

2024-08-08 08:34 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeTest.java
> +    public void newChainCanBeStarted() throws TbNodeException {
please remove this outdated test.

2024-08-08 08:35 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeTest.java
> +        given(ctxMock.transformMsgOriginator(any(TbMsg.class), any(EntityId.class))).willReturn(expectedMsg);
please add a verification to check what will be passed to the transformMsgOriginator method. Add this in other places as well.

2024-08-08 09:05 UTC, ShvaykaD requested changes

2024-08-08 09:05 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/EntitiesByNameAndTypeLoader.java
> +            throw new IllegalStateException("Failed to found " + entityType.name().toLowerCase() + " with name '" + entityName + "'!");
```suggestion
            throw new IllegalStateException("Failed to found " + entityType.getNormalName().toLowerCase() + " with name '" + entityName + "'!");
```

2024-08-08 09:17 UTC, ShvaykaD approved these changes

2024-08-09 12:14 UTC, ViacheslavKlimov requested changes

2024-08-09 12:14 UTC, ViacheslavKlimov commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
>          HashSet<String> knownSources = Sets.newHashSet(CUSTOMER_SOURCE, TENANT_SOURCE, RELATED_SOURCE, ALARM_ORIGINATOR_SOURCE, ENTITY_SOURCE);
Please extract to constant

2024-08-09 12:14 UTC, ViacheslavKlimov commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
> +                log.error("Name pattern should be specified if '{}' source is selected.", ENTITY_SOURCE);
Let's change log level to DEBUG

2024-08-09 12:14 UTC, ViacheslavKlimov commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/EntitiesByNameAndTypeLoader.java
> +            throw new IllegalStateException("Failed to found " + entityType.getNormalName().toLowerCase() + " with name '" + entityName + "'!");
Failed to find*

2024-08-13 07:28 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
> +                log.debug("Relations query should be specified if 'Related entity' source is selected.");
merge if statements. In addition, please add the check for null for: conf.getOriginatorSource()

2024-08-13 08:01 UTC, ShvaykaD approved these changes

2024-08-21 09:06 UTC, ViacheslavKlimov commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/ChangeOriginatorSource.java
> +public enum ChangeOriginatorSource {
Let's rename it to OriginatorSource

2024-08-21 09:12 UTC, ViacheslavKlimov approved these changes

2024-08-21 09:17 UTC, merged