Delay node: improvements
thingsboard/thingsboard pull request #11140
Opened 2024-07-03 13:41 UTC by irynamatveieva

## Pull Request description

- added tests for the delay node
- changed configuration to allow set time unit using patterns
- provided upgrade for the existing nodes
- cover new functionality with tests

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [x] If new yml property was added: make sure a description is added (above or near the property).

2024-08-13 13:30 UTC, dskarzh commented
- Use concurrent hash map instead of normal one, because there is not guarantee that map will always be accessed by the same thread
- Make time unit an enum
- Add correct validation for all configuration fields (period not null, time unit not null and after parsing it is one of the supported values meaning it should not be possible to use microseconds for example, max pending messages is positive and not greater than 100, etc, please consult UI to check how it validates)

2024-08-22 12:11 UTC, dskarzh approved these changes

2024-08-23 08:40 UTC, ShvaykaD requested changes

2024-08-23 08:40 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/delay/TbMsgDelayNodeTest.java
> +                                """
why period was changed from 13 seconds to 60 seconds?

2024-08-23 08:53 UTC, ShvaykaD commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/delay/TbMsgDelayNodeTest.java
> +                                """
> **If there is no useMetadataPeriodInSecondsPatterns then set period to "60"**

This feature didn't exist at the time the rule node was created. So potentially there might be cases where this parameter doesn't exist in the rule node configuration. Non-existing boolean parameters are treated as false during the parse of json config to the configuration class..

2024-08-23 10:21 UTC, ShvaykaD approved these changes

2024-09-12 10:06 UTC, ViacheslavKlimov requested changes

2024-09-12 10:06 UTC, ViacheslavKlimov commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/delay/TbMsgDelayNode.java
> +    private static final String supportedTimeUnitsStr = String.join(",", TimeUnit.SECONDS.name(), TimeUnit.MINUTES.name(), TimeUnit.HOURS.name());
Join supportedTimeUnits.
Also, add a space to "," separator

2024-09-12 10:06 UTC, ViacheslavKlimov commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/delay/TbMsgDelayNode.java
> +        }
Please use javax constraints.

2024-09-12 12:47 UTC, ViacheslavKlimov approved these changes

2024-09-12 12:52 UTC, merged