Added extended functionality for building Modbus connector using UI
thingsboard/thingsboard pull request #11235
Opened 2024-07-18 15:20 UTC by maxunbearable

## Pull Request description

Added extended functionality for building Modbus connector using UI

## General checklist

- [ ] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [ ] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [ ] Description contains human-readable scope of changes.
- [ ] Description contains brief notes about what needs to be added to the documentation.
- [ ] No merge conflicts, commented blocks of code, code formatting issues.
- [ ] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.
  
## Front-End feature checklist

- [ ] Screenshots with affected component(s) are added. The best option is to provide 2 screens: before and after changes;
- [ ] If you change the widget or other API, ensure it is backward-compatible or upgrade script is present.
- [ ] Ensure new API is documented [here](https://github.com/thingsboard/thingsboard-ui-help)

## Back-End feature checklist

- [ ] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [ ] If new dependency was added: the dependency tree is checked for conflicts.
- [ ] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [ ] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [ ] If new yml property was added: make sure a description is added (above or near the property).

2024-07-19 08:30 UTC, vvlladd28 requested changes

2024-07-19 08:30 UTC, vvlladd28 commented on ui-ngx/src/app/shared/directives/ellipsis-chip-list/ellipsis-chip-list.directive.ts
> +    this.intersectionObserver.observe(this.el.nativeElement);
maybe it's better to move it to the constructor of the class?

2024-07-19 08:30 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
> +  slave?: ModbusSlave;
It may be better to rewrite it as a union type with separate types for different connector protocols

2024-07-19 14:57 UTC, vvlladd28 approved these changes

2024-07-23 06:23 UTC, vvlladd28 requested changes

2024-07-23 06:23 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.ts
> +  @Input() isMaster = false;
Need to add decorators @coerceBoolean()

2024-07-23 06:23 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.ts
> +    return this.securityConfigFormGroup.valid || this.disabled ? null : {
```suggestion
    return this.securityConfigFormGroup.valid ? null : {
```

2024-07-23 06:25 UTC, vvlladd28 requested changes

2024-07-23 06:25 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.ts
> +    }
This is an antipattern. You need to implement the method setDisabledState with ControlValueAccessor.

2024-07-24 08:01 UTC, vvlladd28 requested changes

2024-07-24 09:06 UTC, maxunbearable commented on ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.ts
> +        : '',
it has logic for enable/disable, it's inital fields setting

2024-07-24 09:09 UTC, maxunbearable commented on ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-values/modbus-values.component.ts
> +  }
no need to disable form, we just disabling edit buttons for values table

2024-07-25 07:58 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.ts
> +    }
Is it possible not to deserialize the object?

2024-07-25 09:22 UTC, vvlladd28 approved these changes

2024-07-26 14:42 UTC, merged