Oauth2 configuration refactoring
thingsboard/thingsboard pull request #11231
Opened 2024-07-18 09:53 UTC by dashevchenko

## Pull Request description

The existing oauth2 configuration was broken into 3 controllers: DomainController, MobileAppController, Oauth2Controller.

## General checklist

- [ ] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [ ] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [ ] Description contains human-readable scope of changes.
- [ ] Description contains brief notes about what needs to be added to the documentation.
- [ ] No merge conflicts, commented blocks of code, code formatting issues.
- [ ] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.
  
## Front-End feature checklist

- [ ] Screenshots with affected component(s) are added. The best option is to provide 2 screens: before and after changes;
- [ ] If you change the widget or other API, ensure it is backward-compatible or upgrade script is present.
- [ ] Ensure new API is documented [here](https://github.com/thingsboard/thingsboard-ui-help)

## Back-End feature checklist

- [ ] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [ ] If new dependency was added: the dependency tree is checked for conflicts.
- [ ] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [ ] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [ ] If new yml property was added: make sure a description is added (above or near the property).

2024-07-18 10:20 UTC, ViacheslavKlimov commented on common/data/src/main/java/org/thingsboard/server/common/data/audit/ActionType.java
> +    UPDATED_OAUTH2_CLIENTS(false, null);
I think this is redundant, we might not log this at all, only the domain update

2024-08-09 10:24 UTC, vvlladd28 requested changes

2024-08-09 10:24 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client-list.component.ts
Maybe need to use tb-entity-list

2024-08-14 08:57 UTC, vvlladd28 approved these changes

2024-08-15 12:02 UTC, ViacheslavKlimov requested changes

2024-08-16 09:59 UTC, dashevchenko commented on application/src/main/data/upgrade/3.7.0/schema_update.sql
> +            ALTER TABLE oauth2_client RENAME CONSTRAINT oauth2_registration_pkey TO oauth2_client_pkey;
yes, all other will be dropped after column removal

2024-08-16 13:21 UTC, dashevchenko commented on application/src/main/java/org/thingsboard/server/controller/OAuth2Controller.java
> +        }
getOAuth2ClientIds check read permission for each client, so I will just refactor this code

2024-08-16 13:26 UTC, dashevchenko commented on application/src/main/java/org/thingsboard/server/service/edge/EdgeContextComponent.java
> +    private OAuth2ClientService oAuth2ClientService;
@AndriiLandiak could you please take a look

2024-08-16 14:08 UTC, dashevchenko commented on dao/src/main/java/org/thingsboard/server/dao/oauth2/OAuth2ClientDao.java
> +    List<OAuth2Client> findEnabledByPckNameAndPlatformType(String pkgName, PlatformType platformType);
I forgot enabled in query, will fix

2024-08-26 08:14 UTC, ViacheslavKlimov approved these changes

2024-08-26 08:31 UTC, vvlladd28 approved these changes

2024-08-27 09:09 UTC, merged