Added extended functionality for building Socket connector for ThingsBoard IoT Gateway using UI
thingsboard/thingsboard pull request #11378
Opened 2024-08-07 09:35 UTC by Aniutikm

## Pull Request description

Key Changes Showcases:

Socket Configuration
![1](https://github.com/user-attachments/assets/6f23b200-693c-4c9a-b9ed-e6970b4f9ab8)

Devices Configuration
![2](https://github.com/user-attachments/assets/7ca081ac-91b5-4f86-8bf3-1e9744729508)

Device Dialog Configuration
![3](https://github.com/user-attachments/assets/c61a42ee-eeb1-4b2f-b5ff-1be17629bb56)

Time Series Configuration
![4](https://github.com/user-attachments/assets/6ea43e28-84ca-47d3-bad2-a8aea88dc4a3)

Attributes Configuration
![5](https://github.com/user-attachments/assets/76645c4c-ac81-4a1f-9bf4-8d8933fcb703)

Attribute Requests Configuration
![6](https://github.com/user-attachments/assets/6e3e562d-8f55-445b-9250-11a067ae0dd2)

Attribute Updates Configuration
![7](https://github.com/user-attachments/assets/fa1212d3-7837-498a-a389-48545ad69957)

RPC Methods
![8](https://github.com/user-attachments/assets/f7ecf438-62b2-4b3a-b9cf-826d4f0e6f53)

Added hints! 
Address-filter hint added:
![address-filter](https://github.com/user-attachments/assets/5489a9d2-948e-4545-b490-a40545cbe0b4)

Timeseries and Attributes hint added
![key](https://github.com/user-attachments/assets/cb3b6a35-b7fb-42b4-b6c3-163727b6b4ad)

Byte filed hint and popup added
![byte](https://github.com/user-attachments/assets/38ed8547-5164-401a-b3a0-db4169c5320f)

Type hint added
![type](https://github.com/user-attachments/assets/5b8afe0e-295c-463d-b711-3162bbd6ea97)

Request expression popup added 
![RequestExpression](https://github.com/user-attachments/assets/6824df69-6de0-49fb-9d1a-16d8fce02e5b)

Attribute name Expression popup added 
![attributeNameExpression](https://github.com/user-attachments/assets/c83f98c3-9018-4767-a43a-f9d3ea385a6d)

Encoding hint added
![Encoding](https://github.com/user-attachments/assets/51132571-3084-4690-855f-fe46c765bc5c)  

## General checklist

- [ ] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [ ] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [ ] Description contains human-readable scope of changes.
- [ ] Description contains brief notes about what needs to be added to the documentation.
- [ ] No merge conflicts, commented blocks of code, code formatting issues.
- [ ] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.
  
## Front-End feature checklist

- [ ] Screenshots with affected component(s) are added. The best option is to provide 2 screens: before and after changes;
- [ ] If you change the widget or other API, ensure it is backward-compatible or upgrade script is present.
- [ ] Ensure new API is documented [here](https://github.com/thingsboard/thingsboard-ui-help)

## Back-End feature checklist

- [ ] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [ ] If new dependency was added: the dependency tree is checked for conflicts.
- [ ] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [ ] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [ ] If new yml property was added: make sure a description is added (above or near the property).

2024-08-07 10:14 UTC, vvlladd28 requested changes

2024-08-07 10:14 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/socket/devices-config/devices-config.component.ts
This component is a duplicate of the MappingTableComponent. It might be better to reuse the MappingTableComponent

2024-08-07 10:14 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/socket/device-dialog/device-dialog.component.ts
> +  }
It is better to replace https://thingsboard.io with the helpBaseUrl constant

2024-08-07 10:24 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/socket/device-data-keys-pannel/device-data-keys-panel.component.ts
> +        key: ['name', [Validators.required, Validators.pattern(noLeadTrailSpacesRegex)]],
Maybe default value is empty

2024-08-07 15:01 UTC, maxunbearable requested changes

2024-11-01 13:47 UTC, vvlladd28 commented
Added to https://github.com/thingsboard/gateway-management-extensions/pull/4

2024-11-01 13:47 UTC, closed without merging