[Audit logs] - The entityId is null when the alarm deleted
thingsboard/thingsboard pull request #11421
Opened 2024-08-14 11:11 UTC by irynamatveieva

## Pull Request description

- added entityId and originatorId to the audit log details when Type is Deleted
- changed Entity type to Alarm in the audit logs

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [x] If new yml property was added: make sure a description is added (above or near the property).

2024-08-21 09:25 UTC, ShvaykaD requested changes
Please check my comment above.

2024-08-22 10:14 UTC, ShvaykaD requested changes

2024-08-22 10:14 UTC, ShvaykaD commented on dao/src/test/java/org/thingsboard/server/dao/audit/AuditLogServiceImplTest.java
> +        then(entityService).should().fetchEntityName(TENANT_ID, DEVICE_ID);
please verify entity name in auditLogEntry.

2024-08-22 10:14 UTC, ShvaykaD commented on dao/src/test/java/org/thingsboard/server/dao/audit/AuditLogServiceImplTest.java
> +    private AuditLogDataValidator auditLogDataValidator;
unused. Please make it used.

2024-08-22 10:14 UTC, ShvaykaD commented on dao/src/test/java/org/thingsboard/server/dao/audit/AuditLogServiceImplTest.java
> +    private AuditLogSink auditLogSink;
unused. Please make it used.

2024-08-22 13:37 UTC, ShvaykaD requested changes

2024-08-22 13:37 UTC, ShvaykaD commented on common/data/src/main/java/org/thingsboard/server/common/data/audit/ActionType.java
> +    ACTIVATED(), // log string id
```suggestion
    ACTIVATED, // log string id
```

2024-08-23 09:03 UTC, ShvaykaD requested changes
Hi @irynamatveieva, there are some tests that fail in the Alarm Controller Test. Looks related to the changes added in the PR.

2024-08-28 15:47 UTC, ViacheslavKlimov approved these changes

2024-08-28 15:48 UTC, merged