[MQTT transport] Gateway latency API
thingsboard/thingsboard pull request #11607
Opened 2024-09-09 21:02 UTC by YevhenBondarenko

## Pull Request description

 implemented new API for gateway latency

Latency request example:
```
{
    "connectorA": {
        "receivedTs": 1725915119450,
        "publishedTs": 1725915119661
    },
    "connectorB": {
        "receivedTs": 1725915119417,
        "publishedTs": 1725915119661
    }
}
```

Latency check result example:
```
{
    "connectorA": {
        "avgGwLatency": 351,
        "minGwLatency": 145,
        "maxGwLatency": 453,
        "transportLatencyAvg": 13,
        "minTransportLatency": 10,
        "maxTransportLatency": 27
    },
    "connectorB": {
        "avgGwLatency": 285,
        "minGwLatency": 225,
        "maxGwLatency": 346,
        "transportLatencyAvg": 15,
        "minTransportLatency": 10,
        "maxTransportLatency": 27
    }
}
```

## General checklist

- [ ] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [ ] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [ ] Description contains human-readable scope of changes.
- [ ] Description contains brief notes about what needs to be added to the documentation.
- [ ] No merge conflicts, commented blocks of code, code formatting issues.
- [ ] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.
  
## Front-End feature checklist

- [ ] Screenshots with affected component(s) are added. The best option is to provide 2 screens: before and after changes;
- [ ] If you change the widget or other API, ensure it is backward-compatible or upgrade script is present.
- [ ] Ensure new API is documented [here](https://github.com/thingsboard/thingsboard-ui-help)

## Back-End feature checklist

- [ ] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [ ] If new dependency was added: the dependency tree is checked for conflicts.
- [ ] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [ ] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [ ] If new yml property was added: make sure a description is added (above or near the property).

2024-09-10 05:21 UTC, imbeacon commented on common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandler.java
> +            latencyService.process(deviceSessionCtx.getSessionInfo(), gateway.getDeviceId(), JacksonUtil.fromString(payload, new TypeReference<>() {}), ts);
Probably it will be better to use a default behavior, with conversion in adapters, don’t you think so?

2024-09-12 10:13 UTC, ViacheslavKlimov commented on common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/gateway/GatewayLatencyService.java
> +public class GatewayLatencyService {
I think Gateway**Stats**Service is more suitable

2024-09-12 13:01 UTC, ViacheslavKlimov requested changes

2024-09-12 13:16 UTC, ashvayka commented on application/src/main/resources/thingsboard.yml
> +    gateway_metrics_report_interval_sec: "${MQTT_GATEWAY_METRICS_REPORT_INTERVAL_SEC:3600}"
Maybe 1 min by default?

2024-09-12 13:28 UTC, ashvayka commented on common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/gateway/GatewayMetricsService.java
> +        oldStates.clear();
.clear() is not needed. The garbage collector will do the work.

2024-09-12 13:30 UTC, ashvayka commented on common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/gateway/GatewayMetricsService.java
> +        if (states.isEmpty()) {
same error as we faced with device state service. In case of any exceptions, this process will stop working forever.

2024-09-13 07:49 UTC, ViacheslavKlimov requested changes

2024-09-13 07:49 UTC, ViacheslavKlimov commented on common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
> +                    var publishedTs = jo.get("publishedTs").getAsLong();
We should filter out the values that do not have these fields.

2024-09-13 07:49 UTC, ViacheslavKlimov commented on common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
> +       gatewayMetricsService.process(deviceSessionCtx.getSessionInfo(), gateway.getDeviceId(), metricsData, serverReceiveTs);
Don't do any processing if metricsData is empty.

2024-09-13 08:43 UTC, ViacheslavKlimov commented on common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
> +        if (!metadata.isEmpty()) {
metricsData

2024-09-13 09:04 UTC, ViacheslavKlimov approved these changes

2024-09-13 10:04 UTC, ashvayka commented on common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
> +            TransportProtos.PostTelemetryMsg postTelemetryMsg = JsonConverter.convertToTelemetryProto(msg.getAsJsonArray(), metadata);
Please expect that in 99% of the time, the connector latency metadata will be absent. So, we should not create new object ```List<JsonElement> metadata = new ArrayList<>();``` every time. It is better if ```JsonConverter.convertToTelemetryProto``` will be left as ism and we will write a separate method:

JsonConverter.extractMetadata that will return an empty array constant in 99% of the time and a list of GatewayMetadata objects in 1% of the time.

2024-09-16 14:01 UTC, merged