Reduce API usage traffic
thingsboard/thingsboard pull request #12191
Opened 2024-12-04 16:36 UTC by YevhenBondarenko

## Pull Request description
  

## General checklist

- [ ] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [ ] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [ ] Description contains human-readable scope of changes.
- [ ] Description contains brief notes about what needs to be added to the documentation.
- [ ] No merge conflicts, commented blocks of code, code formatting issues.
- [ ] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.
  
## Front-End feature checklist

- [ ] Screenshots with affected component(s) are added. The best option is to provide 2 screens: before and after changes;
- [ ] If you change the widget or other API, ensure it is backward-compatible or upgrade script is present.
- [ ] Ensure new API is documented [here](https://github.com/thingsboard/thingsboard-ui-help)

## Back-End feature checklist

- [ ] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [ ] If new dependency was added: the dependency tree is checked for conflicts.
- [ ] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [ ] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [ ] If new yml property was added: make sure a description is added (above or near the property).

2024-12-09 13:06 UTC, ViacheslavKlimov commented on application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
> +    private void processUsageStatsMsg(List<TbProtoQueueMsg<ToUsageStatsServiceMsgPack>> msgs, TbQueueConsumer<TbProtoQueueMsg<ToUsageStatsServiceMsgPack>> consumer) throws Exception {
Other services are still running and submit the old proto structure.

2024-12-09 13:09 UTC, ViacheslavKlimov commented on common/queue/src/main/java/org/thingsboard/server/queue/usagestats/DefaultTbApiUsageReportClient.java
> +                    var packList = list.subList(i * packSize, Math.min((i + 1) * packSize, list.size()));
`Lists.partition(...)`

2025-01-09 15:36 UTC, smatvienko-tb requested changes
good progress. please do further optimizations

2025-01-09 15:36 UTC, smatvienko-tb commented on common/queue/src/main/java/org/thingsboard/server/queue/usagestats/DefaultTbApiUsageReportClient.java
The good point done is to replace string keys with proto.

I would like to see the resulted message with Kafka UI. To be sure that the output message has no duplicated data.
Unfortunately, I see the duplicated data . Please, visualise the output to proof yourself that the optimisation job done.

here are two hints on the picture. (the service id, tenantId if the customer stats enabled) 

![image](https://github.com/user-attachments/assets/f70e609a-d6f9-474e-8c35-10d9d7a529c3)

2025-01-09 15:36 UTC, smatvienko-tb commented on application/src/main/resources/thingsboard.yml
> +      # Amount of statistic messages in pack
I believe we agreed on 60 seconds by default

2025-01-14 11:14 UTC, YevhenBondarenko commented on common/queue/src/main/java/org/thingsboard/server/queue/usagestats/DefaultTbApiUsageReportClient.java
I agree with serviceId, but with tenantId no, because if we create some group msg per one tenant, this message will include stats from all customers per tenant so this message can be huge and will processed in one tb-core.

2025-02-24 13:52 UTC, ViacheslavKlimov approved these changes

2025-03-03 10:51 UTC, ashvayka commented on application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
> +    private void processUsageStatsMsg(List<TbProtoQueueMsg<ToUsageStatsServiceMsgPack>> msgs, TbQueueConsumer<TbProtoQueueMsg<ToUsageStatsServiceMsgPack>> consumer) throws Exception {
I don't like this at all. You made an important decision and did not even logged it here. How will the system behave when it can't read the data  (in old format) with the new code? Will the administrators see a ton of exceptions in the log? 

The best option is to maintain backward compatibility. You may ignore old messages, but you can't fail to process them. 

The worst option is to rename the topic and use new topic for the data with new format. This will at least avoid tons of error logs.

2025-03-14 12:35 UTC, merged