getEntityTimeseriesValues request addded
thingsboard/thingsboard pull request #3685
Opened 2020-11-06 15:18 UTC by MrKartoshka

public getEntityTimeseriesValues(entityId: EntityId, keys: Array<string>, startTs: number, endTs: number, limit?: number, config?: RequestConfig)
Method was present in version 2.+

2020-11-09 09:04 UTC, vvlladd28 requested changes

2020-11-09 09:04 UTC, vvlladd28 commented on ui-ngx/src/app/core/http/attribute.service.ts
> +      }
You have created an invalid URL query format

2020-11-09 12:08 UTC, ashvayka commented on ui-ngx/src/app/core/http/attribute.service.ts
> +      url += `?startTs=${startTs}`;
It should be '&' instead of '?', right?

2020-11-11 07:13 UTC, ikulikov commented
This is already covered by pull request #3689. Closing.

2020-11-11 07:13 UTC, closed without merging