[3.4] Create Alarm node update the alarm acknowledge status fix
thingsboard/thingsboard pull request #6224
Opened 2022-03-08 20:32 UTC by desoliture1

## Pull Request description

Issue: [#6221](https://github.com/thingsboard/thingsboard/issues/6221)

On alarm update, `Create Alarm` node does not change the alarm status

Was added the `updateStatus` method, which is checking whether the alarm should be acknowledged basing on message data
Was added the corresponding test

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [x] PR name contains fix version. For example, "[3.3.4] Hotfix of some UI component" or "[3.4] New Super Feature".
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [x] Similar PR is opened for PE version to simplify merge. Required for internal contributors only.

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.

2022-03-09 11:23 UTC, ViacheslavKlimov commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateAlarmNode.java
> +    }
Maybe refactor to smth like
```
if (!existingAlarm.getStatus().isAck() && msgAlarm.getStatus().isAck()) {
  if (!existingAlarm.getStatus().isCleared()) {
    newStatus = ACTIVE_ACK;
  } else {
    newStatus = CLEARED_ACK;
}
```
And also, what if the status of existing alarm is `ACTIVE_UNACK` and status in the msg is `CLEARED_ACK`? Maybe we'd need to give an error if existing and new status have different clear status, as there is another node for alarm clearing.

2022-03-11 15:21 UTC, ViacheslavKlimov commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateAlarmNode.java
> +        existingAlarm.setAckTs(System.currentTimeMillis());
What if the status of existing alarm is ACTIVE_UNACK?.. An alarm will just become acknowledged for no reason?

2022-03-14 07:00 UTC, ViacheslavKlimov approved these changes

2022-03-28 11:20 UTC, ashvayka requested changes

2022-03-28 11:20 UTC, ashvayka commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateAlarmNode.java
> +            throw new RuntimeException("The 'Alarm Create' node cannot clear the alarm!");
This breaks backward compatibility. Previously one was able to clear the alarm multiple times. Now this will cause the error.

2022-06-14 16:01 UTC, ashvayka commented
This is half-implemented. The validation is redundant and you set ack time unconditionally.

2022-06-14 16:01 UTC, closed without merging