[WIP][3.4.2] Added ui tests
thingsboard/thingsboard pull request #7670
Opened 2022-11-22 16:24 UTC by Seraphym-Tuhai

## Pull Request description

Put your PR description here instead of this sentence.   

## General checklist

- [ ] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] PR name contains fix version. For example, "[3.3.4] Hotfix of some UI component" or "[3.4] New Super Feature".
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [ ] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [ ] Description contains human-readable scope of changes.
- [ ] Description contains brief notes about what needs to be added to the documentation.
- [ ] No merge conflicts, commented blocks of code, code formatting issues.
- [ ] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Required for internal contributors only.
  
## Front-End feature checklist

- [ ] Screenshots with affected component(s) are added. The best option is to provide 2 screens: before and after changes;
- [ ] If you change the widget or other API, ensure it is backward-compatible or upgrade script is present.
- [ ] Ensure new API is documented [here](https://github.com/thingsboard/thingsboard-ui-help)

## Back-End feature checklist

- [ ] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [ ] If new dependency was added: the dependency tree is checked for conflicts.
- [ ] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [ ] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.

2022-11-28 13:22 UTC, YevhenBondarenko commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/CreateRuleChainTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
We do not use wildcards.

2022-11-28 13:22 UTC, YevhenBondarenko commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/DeleteRuleChainTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
We do not use wildcards.

2022-11-28 13:22 UTC, YevhenBondarenko commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/DeleteSeveralRuleChainsTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
We do not use wildcards.

2022-11-28 13:22 UTC, YevhenBondarenko commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/MakeRuleChainRootTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
We do not use wildcards.

2022-11-28 13:22 UTC, YevhenBondarenko commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/OpenRuleChainTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
We do not use wildcards.

2022-11-28 13:22 UTC, YevhenBondarenko commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/RuleChainEditMenuTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
We do not use wildcards.

2022-11-28 13:22 UTC, YevhenBondarenko commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/SearchRuleChainTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
We do not use wildcards.

2022-11-28 13:22 UTC, YevhenBondarenko commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/SortByNameTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
We do not use wildcards.

2022-11-29 14:18 UTC, Seraphym-Tuhai commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/SortByNameTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
> We do not use wildcards.

done

2022-11-29 14:18 UTC, Seraphym-Tuhai commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/SearchRuleChainTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
> We do not use wildcards.

done

2022-11-29 14:18 UTC, Seraphym-Tuhai commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/RuleChainEditMenuTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
> We do not use wildcards.

done

2022-11-29 14:18 UTC, Seraphym-Tuhai commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/OpenRuleChainTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
> We do not use wildcards.

done

2022-11-29 14:18 UTC, Seraphym-Tuhai commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/MakeRuleChainRootTest.java
> +import static org.thingsboard.server.msa.ui.utils.Const.*;
> We do not use wildcards.

done

2022-11-29 14:19 UTC, Seraphym-Tuhai commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/SortByNameTest.java
> +        ;
> remove

done

2022-11-29 14:19 UTC, Seraphym-Tuhai commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/RuleChainEditMenuTest.java
> +        ;
> remove

done

2022-11-29 14:19 UTC, Seraphym-Tuhai commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/ruleChainsSmoke/CreateRuleChainImportTest.java
> +        ;
> remove

done

2022-11-29 14:19 UTC, Seraphym-Tuhai commented on msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/base/AbstractDiverBaseTest.java
> +    private static final boolean HEADLESS = false;
> headless should be true by default.

done

2022-12-09 13:46 UTC, YevhenBondarenko commented on msa/black-box-tests/src/test/resources/smokesRuleChain.xml
> +    Copyright � 2016-2022 The Thingsboard Authors
use mvn license:format before `push`

2022-12-12 08:23 UTC, YevhenBondarenko approved these changes

2022-12-12 15:59 UTC, smatvienko-tb requested changes

2022-12-12 15:59 UTC, smatvienko-tb commented on msa/black-box-tests/src/test/resources/docker-selenium.yml
> +    extra_hosts:
An explicit IP address may cause problems in different environments. You never know what IP address/network will be assigned by the host systems.

2022-12-23 08:59 UTC, YevhenBondarenko approved these changes

2022-12-26 14:50 UTC, merged