[WIP] [3.5] Oauth2 for mail server
thingsboard/thingsboard pull request #7989
Opened 2023-01-25 10:30 UTC by dashevchenko

## Pull Request description

Added new type of authentiction for admin mail settings - oauth2. 

## General checklist

- [ ] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] PR name contains fix version. For example, "[3.3.4] Hotfix of some UI component" or "[3.4] New Super Feature".
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [ ] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [ ] Description contains human-readable scope of changes.
- [ ] Description contains brief notes about what needs to be added to the documentation.
- [ ] No merge conflicts, commented blocks of code, code formatting issues.
- [ ] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Required for internal contributors only.
  
## Front-End feature checklist

- [ ] Screenshots with affected component(s) are added. The best option is to provide 2 screens: before and after changes;
- [ ] If you change the widget or other API, ensure it is backward-compatible or upgrade script is present.
- [ ] Ensure new API is documented [here](https://github.com/thingsboard/thingsboard-ui-help)

## Back-End feature checklist

- [ ] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [ ] If new dependency was added: the dependency tree is checked for conflicts.
- [ ] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [ ] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.

2023-03-13 09:25 UTC, YevhenBondarenko commented on dao/src/main/java/org/thingsboard/server/dao/nosql/CassandraAbstractDao.java
> +            statement = statement.setConsistencyLevel(level);
how its related to the oauth2 feature?

2023-03-13 11:53 UTC, YevhenBondarenko approved these changes

2023-03-16 09:31 UTC, vvlladd28 approved these changes

2023-03-31 08:36 UTC, vvlladd28 requested changes

2023-03-31 08:36 UTC, vvlladd28 commented on ui-ngx/src/app/core/http/admin.service.ts
> +  public getMailConfigTemplate(config?: RequestConfig): Observable<Array<any>> {
Why does the function return type any?

2023-03-31 08:36 UTC, vvlladd28 commented on ui-ngx/src/assets/locale/locale.constant-en_US.json
> +          "smtp-provider": "SMTP provider",
You can break ui component oauth2-settings

2023-03-31 08:36 UTC, vvlladd28 commented on ui-ngx/src/app/shared/models/oauth2.models.ts
> +);
This setting must be with getMailConfigTemplate

2023-03-31 08:36 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/pages/admin/mail-server.component.ts
> +      error => this.store.dispatch(new ActionNotificationShow({message: error.error.message, type: 'error'}))
Need to rewrite in new style subscription

2023-03-31 08:36 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/pages/admin/mail-server.component.ts
> +  private parseUrl(value: string) {
What type does the function return?

2023-03-31 08:36 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/pages/admin/mail-server.component.ts
> +  get accessTokenButtonName() {
What type does the function return?

2023-03-31 08:36 UTC, vvlladd28 commented on ui-ngx/src/app/modules/home/pages/admin/mail-server.component.ts
> +  get accessTokenStatus() {
What type does the function return?

2023-04-07 15:35 UTC, ashvayka commented
@dashevchenko , unfortunately, we need to postpone this feature to 3.5.1 since it is not yet ready. Please resolve conflicts and prepare this for merge to 3.5.1

2023-04-25 14:01 UTC, vvlladd28 approved these changes

2023-06-09 10:12 UTC, closed without merging