Added controller method to retrieve list of commands to publish device telemetry
thingsboard/thingsboard pull request #8803
Opened 2023-06-21 13:06 UTC by dashevchenko

## Pull Request description

Added method  to DeviceController that retrieves list of possible commands to publish device telemetry.

## General checklist

- [ ] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [ ] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [ ] Description contains human-readable scope of changes.
- [ ] Description contains brief notes about what needs to be added to the documentation.
- [ ] No merge conflicts, commented blocks of code, code formatting issues.
- [ ] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.
  
## Front-End feature checklist

- [ ] Screenshots with affected component(s) are added. The best option is to provide 2 screens: before and after changes;
- [ ] If you change the widget or other API, ensure it is backward-compatible or upgrade script is present.
- [ ] Ensure new API is documented [here](https://github.com/thingsboard/thingsboard-ui-help)

## Back-End feature checklist

- [ ] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [ ] If new dependency was added: the dependency tree is checked for conflicts.
- [ ] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [ ] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.

2023-06-26 11:03 UTC, YevhenBondarenko approved these changes

2023-07-05 13:10 UTC, YevhenBondarenko commented on application/src/main/resources/thingsboard.yml
> +# Device connectivity properties to publish telemetry
Plz add ability to enable/disable per each protocol
security protocols by default should be disabled

2023-07-05 13:12 UTC, YevhenBondarenko commented on dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityInfo.java
> +
extra line

2023-07-05 13:22 UTC, YevhenBondarenko commented on dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
> +            case X509_CERTIFICATE:
plz remove x509

2023-07-05 13:26 UTC, YevhenBondarenko commented on application/src/main/java/org/thingsboard/server/controller/DeviceController.java
> +    @ApiOperation(value = "Get commands to publish device telemetry (getDevicePublishTelemetryCommands)",
plz add response example for swagger

2023-07-05 13:30 UTC, YevhenBondarenko commented on dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
> +            return String.format("curl -v -X POST %s/api/v1/%s/telemetry --header Content-Type:application/json --data " + PAYLOAD,
you should use base url only if host from config is null

2023-07-05 13:32 UTC, YevhenBondarenko commented on dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
> +        command.append(" -h ").append(mqttProps.getHost());
if host is null you should use base url, the same for port. Plz check other protocols!

2023-07-07 09:06 UTC, ViacheslavKlimov requested changes

2023-07-07 09:06 UTC, ViacheslavKlimov commented on application/src/main/resources/thingsboard.yml
> +      port: "${DEVICE_CONNECTIVITY_COAPS_PORT:5684}"
Double-check the env variables names, you've used DEVICE_CONNECTIVITY_MQTT_ENABLED for mqtts, coap and coaps

2023-07-07 09:06 UTC, ViacheslavKlimov commented on dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
> +    public Map<String, String> findDevicePublishTelemetryCommands(String baseUrl, Device device) throws URISyntaxException {
Consider to move this functionality to a separate service. DeviceServiceImpl is already pretty big

2023-07-10 11:04 UTC, YevhenBondarenko approved these changes

2023-07-20 12:39 UTC, merged