Fix trim double quotes for RestApiCallNode
thingsboard/thingsboard pull request #9534
Opened 2023-10-31 13:08 UTC by AndriiLandiak

## Pull Request description

_Issue:_ Currently, the RestApiCallNode features a configuration field labeled "trimDoubleQuotes." However, this approach has proven problematic. It does not adequately handle situations where specific symbols like newline characters \n, tabs \t, curly braces {}, square brackets [], and others are present in the serialized message.

_Fix:_ To address this issue, we should implement a more robust solution. Specifically, we should perform deserialization after the message has been serialized within the unbindMsg() method of the RuleNodeScriptEngine (JacksonUtil.toString()). 
This deserialization process should make use of JacksonUtil.fromString(). To ensure the correctness of this approach, comprehensive tests have been provided to cover scenarios involving these special symbols.

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [x] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.
  

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [x] If new yml property was added: make sure a description is added (above or near the property).

2023-10-31 16:04 UTC, smatvienko-tb requested changes
Hey!
This fix makes perfect sense, as we discussed in the morning. 

But for the product, it requires more effort from You.
Please find my comments below.

2023-10-31 16:04 UTC, smatvienko-tb commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
> +    protected String trimDoubleQuotesIfRequired(String data) {
1. The feature has to be renamed to make more sense. as it acts as JSON.parse to make plain/text from JSON string.
2. UI and description and documentation have to be adjusted.
3. the method getData should get `getConfig().isTrimDoubleQuotes()`as a boolean parameter. This make your code better and much easier to test without excessive mocking

2023-10-31 16:04 UTC, smatvienko-tb commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
> +    private String getData(TbMsg tbMsg) {
the method seems useless

2023-10-31 16:04 UTC, smatvienko-tb commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbHttpClientTest.java
> +        config = mock(TbRestApiCallNodeConfiguration.class);
I guess this is not necessary, just make a refactoring of the subject method

2023-10-31 16:04 UTC, smatvienko-tb commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbHttpClientTest.java
> +    @Test
Please, make a parametrized test

2023-10-31 16:12 UTC, smatvienko-tb commented
as a reference:

JSON.stringify()
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

JSON.parse()
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

2023-10-31 16:13 UTC, smatvienko-tb commented
please, add in the description that the current implementation are not allowed to send a correct **plain/text** payload

2023-11-01 08:00 UTC, ashvayka commented
Let's analyze the headers configured by the user. If we are sending the JSON ("Content-type" = "application/json;charset=UTF-8"), we should create an HTTPEntity with correct type and use it. We can also apply validation that we have a valid JSON before posting it. IF we are sending the request as plain/text then we should convert it to String. 
See more here: https://www.baeldung.com/spring-resttemplate-post-json#2-handling-character-encoding

2023-11-07 11:22 UTC, smatvienko-tb reviewed
Please, find some minor notes below

2023-11-07 11:22 UTC, smatvienko-tb commented on rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbHttpClientTest.java
> +    @MethodSource("provideParameters")
Please, use
`@ValueSource(strings = {"", "  "})`
for primitive types

2023-11-07 11:22 UTC, smatvienko-tb commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
> +    protected String parseJsonStringToPlainText(String data, boolean parseToJson) {
it looks like the method doing something only for parseToJson == true
It makes sense to move such a case upper and not fire the method if parseToJson == false

2023-11-07 11:22 UTC, smatvienko-tb commented on rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
> +    protected String parseJsonStringToPlainText(String data, boolean parseToJson) {
I see there is "no body" configuration present. This means parsing data makes no sense at all when "no body" == true

2023-11-07 13:17 UTC, merged